Feat: Implement signup page
Bang-Soal/dijkstra pull request #5
Opened 2023-12-24 17:00 UTC by catherineeangel

# Description
Implement main signup page. 

## Routes 
1. /signup
params:
- login: show login form
- onboard: show onboard form
without the params it will show just signup form (it is the same with login with different api handlers)

## UI
1. login, signup with otp token verification
<img width="378" alt="Screenshot 2023-12-24 at 23 53 11" src="https://github.com/Bang-Soal/dijkstra/assets/76489185/e190f566-f736-48ec-a924-312a7cbdb54b">

<img width="376" alt="Screenshot 2023-12-24 at 21 51 55" src="https://github.com/Bang-Soal/dijkstra/assets/76489185/baeda6c5-6a13-4daf-90d0-0766e308380e">
<img width="1440" alt="Screenshot 2023-12-24 at 23 51 31" src="https://github.com/Bang-Soal/dijkstra/assets/76489185/aab5eed2-8a5a-4f29-806b-313b43641c86">
<img width="1440" alt="Screenshot 2023-12-24 at 23 52 54" src="https://github.com/Bang-Soal/dijkstra/assets/76489185/95ba2c8b-4e7f-46db-b392-dd6f846cfe7a">

2. onboard

https://github.com/Bang-Soal/dijkstra/assets/76489185/c465ba08-82f7-4d68-be34-74430a751545

2023-12-24 19:50 UTC, umarez requested changes

2023-12-24 19:50 UTC, umarez commented on src/app/components/AuthGuard.tsx
> +    skip: !!user.profile || isAuthPath,
why the query skip when user.profile exist?

2023-12-24 19:50 UTC, umarez commented on src/app/components/SectionSignUp.tsx
> +    redirect("/signup?login=true");
what is the query params for

2023-12-24 19:50 UTC, umarez commented on src/app/components/SectionSignUp.tsx
> +              window.open(`${process.env.NEXT_PUBLIC_API_URL}/auth/google`);
no need this since we wont utilize google login

2023-12-24 19:50 UTC, umarez commented on src/app/components/constants.ts
> +export const AVAILABLE_PATHS = [...AUTH_PATHS, "/", "/langganan"];
move this to seperate standalone file (paths)

2023-12-24 19:50 UTC, umarez commented on src/app/signup/Authentication.tsx
> +"use client";
Change this filename & component to AuthenticationContainer

2023-12-24 19:50 UTC, umarez commented on src/app/signup/SignupForm.tsx
> +                                <Input placeholder="Phone Number" {...field} />
make sure input type is number only

2023-12-24 19:50 UTC, umarez commented on src/app/signup/SignupForm.tsx
> +      sendOTP({ phone_number: values.phone_number }).then(() => {});
use async await

2023-12-24 19:50 UTC, umarez commented on src/app/signup/Authentication.tsx
> +  const onboard = searchParams.get("onboard");
please guard it if the user already onboarded. It's better to create separate onboarding page

2023-12-24 19:50 UTC, umarez commented on src/types/users.ts
> +export type OnboardRequest = {
```suggestion
export type UserOnboardRequest = {
```

2023-12-25 01:35 UTC, catherineeangel commented on src/app/signup/SignupForm.tsx
> +                                <Input placeholder="Phone Number" {...field} />
this will go thru validation with the SigninFormSchema, this validates that the input is digits only, and some standard indo phone number validation

2023-12-25 01:38 UTC, catherineeangel commented on src/app/signup/Authentication.tsx
> +  const onboard = searchParams.get("onboard");
okay, for guarding i alr made AuthGuard component. will update it later

2023-12-25 01:40 UTC, catherineeangel commented on src/app/components/SectionSignUp.tsx
> +    redirect("/signup?login=true");
just an option to show the login section form, although it is the same field with signin, just different api handlers

2023-12-25 01:51 UTC, catherineeangel commented on src/app/components/AuthGuard.tsx
> +    skip: !!user.profile || isAuthPath,
so it can use the data from redux state

2023-12-25 05:09 UTC, umarez requested changes

2023-12-25 08:41 UTC, catherineeangel commented on src/app/(authentication)/signup/interface.ts
> +  one: PTN | null;
its for the initial value, but there is alr a validation schema that makes the first ptn and major required

2023-12-25 09:00 UTC, umarez approved these changes

2023-12-25 09:02 UTC, umarez commented on src/app/signup/SignupForm.tsx
> +                                <Input placeholder="Phone Number" {...field} />
👍

2023-12-25 10:02 UTC, umarez requested changes

2023-12-25 10:02 UTC, umarez commented on src/app/components/withAuth.tsx
> +    const isAuthPath = AUTH_PATHS.some((path) => path === pathname);
we dont need this right? the HOC is only used for the pages that need authentications

2023-12-25 10:37 UTC, umarez requested changes

2023-12-25 10:37 UTC, umarez commented on src/app/components/withAuth.tsx
> +      redirect("/signup");
why redirect to `signup` instead of `login` page?

2023-12-25 12:57 UTC, merged